### ISSUE TITLE
bot cant play anything

### ISSUE THREAD

**Issue by rezanr81nn** [moonstar-x/discord-music-24-7#2]
(7:01:22 PM) - [ERROR] - Error: input stream: Status code: 429

at StreamDispatcher.dispatcher.on.err (/app/src/app.js:74:14)

    at StreamDispatcher.emit (events.js:194:15)

    at streamError (/rbd/pnpm-volume/fe128fbf-e057-4865-9abc-dcd71a24cf28/node_modules/.github.com/discordjs/discord.js/ea9e1441905e67e2627a6f5e80a8d989d01376c5/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:88:14)

    at PassThrough.StreamDispatcher.streams.input.on.err (/rbd/pnpm-volume/fe128fbf-e057-4865-9abc-dcd71a24cf28/node_modules/.github.com/discordjs/discord.js/ea9e1441905e67e2627a6f5e80a8d989d01376c5/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:94:67)

    at PassThrough.emit (events.js:189:13)

    at ytdl.getInfo (/rbd/pnpm-volume/fe128fbf-e057-4865-9abc-dcd71a24cf28/node_modules/.registry.npmjs.org/ytdl-core/0.29.7/node_modules/ytdl-core/lib/index.js:19:14)

    at fn (/rbd/pnpm-volume/fe128fbf-e057-4865-9abc-dcd71a24cf28/node_modules/.registry.npmjs.org/ytdl-core/0.29.7/node_modules/ytdl-core/lib/info.js:370:25)

    at exports.getBasicInfo (/rbd/pnpm-volume/fe128fbf-e057-4865-9abc-dcd71a24cf28/node_modules/.registry.npmjs.org/ytdl-core/0.29.7/node_modules/ytdl-core/lib/info.js:212:21)

    at fn (/rbd/pnpm-volume/fe128fbf-e057-4865-9abc-dcd71a24cf28/node_modules/.registry.npmjs.org/ytdl-core/0.29.7/node_modules/ytdl-core/lib/info.js:370:25)

**Comment by moonstar-x** [comment]
It seems to be an issue with `ytdl-core`. Some people are having the same error as you https://github.com/fent/node-ytdl-core/issues/444, I recommend you update `ytdl-core` but I think it's caused bya breaking change at youtube itself.

**Comment by moonstar-x** [comment]
Closed due to inactivity.
