### ISSUE TITLE
Error input Stream

### ISSUE THREAD

**Issue by Pi0Ant0ni0** [moonstar-x/discord-music-24-7#23]
```
[ERROR] -  Error: input stream: Unable to retrieve video metadata                                                                            
    at getJSONWatchPage (/home/pi0/discord-music-24-7/node_modules/ytdl-core/lib/info.js:184:11)                                                          
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getBasicInfo (/home/pi0/discord-music-24-7/node_modules/ytdl-core/lib/info.js:34:14)                                                 
    at async Map.getOrSet (/home/pi0/discord-music-24-7/node_modules/ytdl-core/lib/cache.js:24:19)                                                        
    at async exports.getInfo (/home/pi0/discord-music-24-7/node_modules/ytdl-core/lib/info.js:252:14)                                                     
    at async Map.getOrSet (/home/pi0/discord-music-24-7/node_modules/ytdl-core/lib/cache.js:24:19)                                  
```
i am having this issue, i do not know why, is the first time that i try to host/run a discord bot so i do know nothing about.

**Comment by moonstar-x** [comment]
I'm gonna check a bit further into this since someone else reported this to me directly.

Thanks for your report!

**Comment by moonstar-x** [comment]
I tried doing this and I got the error. Once I updated `ytdl-core` the error was gone.

Try pulling the changes from master with `git pull origin master`,
Then remove the `node_modules` folder with `rm -rf node_modules`
And re-install the dependencies: `npm install`

Try that and tell me if you still get the error so I can close this issue! :)

**Comment by Pi0Ant0ni0** [comment]
thanks man it worked!

**Comment by moonstar-x** [comment]
Glad it worked!
