### ISSUE TITLE
I received this error when starting the Bot on Glitch.

### ISSUE THREAD

**Issue by ShadowsPlayer** [moonstar-x/discord-music-24-7#81]
(3:48:34 PM) - [FATAL] -  VoiceChannelError: Something went wrong when trying to look for the channel I was supposed to join.
    at Player.initialize (/app/src/classes/Player.js:84:13)
    at processTicksAndRejections (internal/process/task_queues.js:88:5) {
  name: 'VoiceChannelError'
}

**Comment by moonstar-x** [comment]
Hi, have you by any chance added your own configuration in the `settings.json` file inside the config folder?

The error says that the channel_id is incorrect, so make sure that the ID that you added the correct ID for the channel. Make sure that the bot is inside the server where the channel is located and also that the bot has enough permissions to join the channel.
